# Generated by Django 2.2.4 on 2019-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Prosecutor'), (3, 'Secretary'), (4, 'Victim Advocate'), (5, 'Paralegal')], null=True),
        ),
    ]
