# Generated by Django 2.2.4 on 2019-09-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190903_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.IntegerField(choices=[(2, 'Prosecutor'), (3, 'Secretary'), (4, 'Victim Advocate'), (5, 'Paralegal')], null=True),
        ),
    ]
