# Generated by Django 2.1.5 on 2019-08-08 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('cr_number', models.CharField(max_length=20, unique=True)),
                ('defense_attorney', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(default='')),
                ('track', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('arraignment_date', models.DateTimeField(null=True)),
                ('scheduling_conference_date', models.DateTimeField(null=True)),
                ('pti_request_date', models.DateTimeField(null=True)),
                ('trial_date', models.DateTimeField(null=True)),
                ('stayed', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_case_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mdc_num', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('birth_date', models.DateField()),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(max_length=11, unique=True)),
                ('fbi_number', models.CharField(blank=True, max_length=9, null=True)),
                ('state_id', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tier', models.IntegerField(blank=True, choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_defendant_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_defendant_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_judge_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_judge_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'In Limine'), (1, 'Review Conditions of Release'), (2, 'Motion to Suppress Witness'), (3, 'Motion to Suppress Evidence'), (4, 'Motion to Suppress Witness and Evidence'), (5, 'Motion to Dismiss'), (6, 'Motion to Suppress and Dismiss'), (7, 'Motion to Extend Deadline'), (8, 'Motion to Reconsider'), (9, 'Other')])),
                ('date_received', models.DateTimeField()),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('date_hearing', models.DateTimeField(blank=True, null=True)),
                ('response_filed', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='defendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Defendant'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Judge'),
        ),
        migrations.AddField(
            model_name='case',
            name='prosecutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_case_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
