# Generated by Django 2.2.4 on 2019-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190903_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defenseattorney',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='defenseattorney',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.CharField(default='DEFAULT DEFENDANT', max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Defendant',
        ),
        migrations.DeleteModel(
            name='DefenseAttorney',
        ),
    ]
