# Generated by Django 2.2.4 on 2019-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190904_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pti_conduct_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='pti_request_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
