# Generated by Django 2.1.5 on 2019-05-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20)),
                ('track', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('prosecutor_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('prosecutor_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('paralegal_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('paralegal_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('supervisor_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('supervisor_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('arraignment_date', models.DateTimeField(blank=True, null=True)),
                ('scheduling_conference_date', models.DateTimeField(blank=True, null=True)),
                ('pti_request_date', models.DateTimeField(blank=True, null=True)),
                ('trial_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'FFA'), (1, 'Scheduling Conference'), (2, 'Witness List'), (3, 'Request PTIs'), (4, 'Conduct Initial PTIs'), (5, 'Winess PTIs'), (6, 'Scientific Evidence'), (7, 'Pretrial Motion Filing'), (8, 'Pretrial Motion Response'), (9, 'Pretrial Motion Hearing'), (10, 'Pretrial Conference'), (11, 'Final Witness List'), (12, 'Need for Interpreter'), (13, 'Plea Agreement'), (14, 'Trial')])),
                ('date', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remind.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
