# Generated by Django 2.1.5 on 2019-08-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cr_number',
            field=models.CharField(default='default', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
