# Generated by Django 2.1.5 on 2019-05-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='paralegal_first_name',
            new_name='paralegal_name',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='prosecutor_first_name',
            new_name='prosecutor_name',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='supervisor_first_name',
            new_name='supervisor_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='paralegal_last_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='prosecutor_last_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='supervisor_last_name',
        ),
    ]
