# Generated by Django 2.1.5 on 2019-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0002_auto_20190606_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Complete'), (2, 'Expired')], default=0),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='type',
            field=models.IntegerField(choices=[(0, 'FFA'), (1, 'Scheduling Conference'), (2, 'Witness List'), (3, 'Defense Request PTIs'), (4, 'Defense Conduct PTIs'), (5, 'Witness PTIs'), (6, 'Scientific Evidence'), (7, 'Pretrial Motion Filing'), (8, 'Pretrial Motion Response'), (9, 'Pretrial Motion Hearing'), (10, 'Pretrial Conference'), (11, 'Final Witness List'), (12, 'Need for Interpreter'), (13, 'Plea Agreement'), (14, 'Trial')]),
        ),
    ]
