# Generated by Django 2.1.5 on 2019-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0002_auto_20190719_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='stayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='type',
            field=models.IntegerField(choices=[(0, 'FFA'), (1, 'Scheduling Conference'), (2, 'Initial Witness List'), (3, 'PTIs Requested'), (4, 'PTIs Conducted'), (5, 'Witness PTIs'), (6, 'Scientific Evidence'), (7, 'Pretrial Motion Filing'), (8, 'Pretrial Motion Response'), (9, 'Pretrial Motion Hearing'), (10, 'PTC/Docket Call'), (11, 'Final Witness List'), (12, 'Need for Interpreter'), (13, 'Plea Agreement'), (14, 'Trial')]),
        ),
    ]
