# Generated by Django 2.1.5 on 2019-08-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0003_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='remind.Judge'),
        ),
    ]
