# Generated by Django 2.1.5 on 2019-08-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0004_auto_20190806_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='judge',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
    ]
