# Generated by Django 2.1.5 on 2019-08-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remind', '0005_auto_20190806_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mdc_num', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True, unique=True)),
                ('fbi_number', models.CharField(blank=True, max_length=9, null=True)),
                ('state_id', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tier', models.IntegerField(blank=True, choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_defendant_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_defendant_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='remind.Defendant'),
        ),
    ]
