# Generated by Django 2.1.5 on 2019-08-07 21:09

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0006_auto_20190807_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(max_length=11, unique=True),
        ),
    ]
