# Generated by Django 2.1.5 on 2019-08-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0007_auto_20190807_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='case',
            name='defendant',
        ),
        migrations.RemoveField(
            model_name='case',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='case',
            name='prosecutor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='case',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='case',
        ),
        migrations.AlterField(
            model_name='deadline',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Motion'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Defendant',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Motion',
        ),
    ]
