# Generated by Django 2.1.5 on 2019-08-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0008_defenseattorney'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseattorney',
            name='firm',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
