# Generated by Django 2.1.5 on 2019-08-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0009_defenseattorney_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='defense_attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='remind.DefenseAttorney'),
        ),
    ]
