# Generated by Django 2.1.5 on 2019-08-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0010_auto_20190807_1627'),
        ('remind', '0008_auto_20190808_1419'),
    ]

    operations = [
    ]
