# Generated by Django 2.1.5 on 2019-08-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0011_merge_20190808_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defenseattorney',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='defenseattorney',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DefenseAttorney',
        ),
    ]
